blank_issues_enabled: false
contact_links:
  - name: Bug in Meilisearch
    url: https://github.com/meilisearch/meilisearch/issues
    about: Please report issues regarding Meilisearch in the dedicated repository
  - name: Support questions & other
    url: https://discord.meilisearch.com/
    about: Support is not handled here but on our Discord
