name: Deploy to Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        yarn
        yarn build
      env:
        REACT_APP_MEILI_SERVER_ADDRESS: ${{ secrets.REACT_APP_MEILI_SERVER_ADDRESS }}
        REACT_APP_MEILI_API_KEY: ${{ secrets.REACT_APP_MEILI_API_KEY }}
        REACT_APP_FATHOM_TRACKING_CODE: ${{ secrets.REACT_APP_FATHOM_TRACKING_CODE }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
